=== seafewd/XML_Stuff/out/production/XML/AddressBook/addressbook.xsd
<?xml version="1.0"?>
<!-- file addressbook.xsd -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:ab="http://www.example.org/addresses"
            targetNamespace="http://www.example.org/addresses"
            elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xsd:element name="addressbook">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="address" type="ab:Address" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Address">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="street" type="xsd:string"/>
            <xsd:element name="city" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="category" type="xsd:string"/>
    </xsd:complexType>

</xsd:schema>

=== seafewd/XML_Stuff/out/production/XML/AddressBook/addressbook.xml
<?xml version="1.0"?>
<!-- file addressbook.xml -->

<ab:addressbook xmlns:ab="http://www.example.org/addresses"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.example.org/addresses addressbook.xsd">

    <ab:address category="home">
        <ab:name>Alice Smith</ab:name>
        <ab:street>123 Maple Street</ab:street>
        <ab:city>Mill Valley</ab:city>
    </ab:address>

    <ab:address category="office">
        <ab:name>Helen Zoe</ab:name>
        <ab:street>47 Eden Street</ab:street>
        <ab:city>Cambridge</ab:city>
    </ab:address>

</ab:addressbook>
