=== seafewd/XML_Stuff/src/jaxbFiles/schema1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book">
        <xs:complexType>
          <xs:sequence>
            <xs:element name = "title" type="xs:string" />
            <xs:element name = "author" type="xs:string" />
            <xs:element name = "publishedDate" type="xs:string" />
            <xs:element name = "pages" type="xs:int" />
            <xs:element name = "chapters" type="xs:int" />
          </xs:sequence>
        </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== seafewd/XML_Stuff/src/BookCatalog/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- root node -->
<catalog xmlns="https://www.w3schools.com"
         xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xs:schemaLocation="https://www.w3schools.com schema1.xsd">

    <book>
        <title>Fisker</title>
        <author>Alex</author>
        <publishedDate>today</publishedDate>
        <pages>490</pages>
        <chapters>35</chapters>
    </book>

    <book>
        <title>Fisker</title>
        <author>Alex</author>
        <publishedDate>today</publishedDate>
        <pages>490</pages>
        <chapters>35</chapters>
    </book>

    <book>
        <title>Fisker</title>
        <author>Alex</author>
        <publishedDate>today</publishedDate>
        <pages>490</pages>
        <chapters>35</chapters>
    </book>

    <book>
        <title>Fisker</title>
        <author>Alex</author>
        <publishedDate>today</publishedDate>
        <pages>490</pages>
        <chapters>35</chapters>
    </book>

</catalog>
